# tabs/images.py
import streamlit as st
from brief import build_prompt_from_brief
from image_pipeline import get_provider

def render(orientation: str, target_wwr: float, budget: str, provider_name: str):
    st.subheader("이미지 (AI 생성)")
    prov = get_provider(provider_name)

    base_prompt = build_prompt_from_brief(st.session_state.brief, orientation, target_wwr, budget)
    prompt_txt = st.text_area("최종 프롬프트", value=base_prompt, height=160)

    if st.button("이미지 생성"):
        img_bytes = prov.generate_image_bytes(prompt=prompt_txt)
        st.image(img_bytes, caption=f"Generated by {prov.name}", use_column_width=True)
